//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("ACTIVITY", Schema = "openehr")]
    public partial class ACTIVITY : LOCATABLE
    {
        
        private ITEM_STRUCTURE descriptionField;
        
        private DV_PARSABLE timingField;
        
        private string action_archetype_idField;
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual ITEM_STRUCTURE description
        {
            get
            {
                return descriptionField;
            }
            set
            {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_PARSABLE timing
        {
            get
            {
                return timingField;
            }
            set
            {
                this.timingField = value;
                this.RaisePropertyChanged("timing");
            }
        }
        
        [MaxLength(4000)]
        public virtual string action_archetype_id
        {
            get
            {
                return this.action_archetype_idField;
            }
            set
            {
                this.action_archetype_idField = value;
                this.RaisePropertyChanged("action_archetype_id");
            }
        }
    }
}
