//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("ACTION", Schema = "openehr")]
    public partial class ACTION : CARE_ENTRY
    {
        
        private DV_DATE_TIME timeField;
        
        private ITEM_STRUCTURE descriptionField;
        
        private ISM_TRANSITION ism_transitionField;
        
        private INSTRUCTION_DETAILS instruction_detailsField;
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_DATE_TIME time
        {
            get
            {
                return timeField;
            }
            set
            {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual ITEM_STRUCTURE description
        {
            get
            {
                return descriptionField;
            }
            set
            {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual ISM_TRANSITION ism_transition
        {
            get
            {
                return ism_transitionField;
            }
            set
            {
                this.ism_transitionField = value;
                this.RaisePropertyChanged("ism_transition");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual INSTRUCTION_DETAILS instruction_details
        {
            get
            {
                return instruction_detailsField;
            }
            set
            {
                this.instruction_detailsField = value;
                this.RaisePropertyChanged("instruction_details");
            }
        }
    }
}
