//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    /// <summary>
    /// Required properties: term_definitions
    /// </summary>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("ARCHETYPE_ONTOLOGY", Schema = "openehr")]
    public partial class ARCHETYPE_ONTOLOGY : System.ComponentModel.INotifyPropertyChanged
    {
        
        private CodeDefinitionSetCollection term_definitionsField;
        
        private CodeDefinitionSetCollection constraint_definitionsField;
        
        private TermBindingSetCollection term_bindingsField;
        
        private ConstraintBindingSetCollection constraint_bindingsField;
        
        [System.Xml.Serialization.XmlElementAttribute("term_definitions")]
        [Barcline.Core.MaxOccurs("unbounded")]
        [Required()]
        public virtual CodeDefinitionSetCollection term_definitions
        {
            get
            {
                if (term_definitionsField == null)
                {
                    this.term_definitionsField = new CodeDefinitionSetCollection();
                }
                return term_definitionsField;
            }
            set
            {
                this.term_definitionsField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("term_definitions");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("constraint_definitions")]
        [Barcline.Core.MinOccurs("0")]
        [Barcline.Core.MaxOccurs("unbounded")]
        public virtual CodeDefinitionSetCollection constraint_definitions
        {
            get
            {
                if (constraint_definitionsField == null)
                {
                    this.constraint_definitionsField = new CodeDefinitionSetCollection();
                }
                return constraint_definitionsField;
            }
            set
            {
                this.constraint_definitionsField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("constraint_definitions");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("term_bindings")]
        [Barcline.Core.MinOccurs("0")]
        [Barcline.Core.MaxOccurs("unbounded")]
        public virtual TermBindingSetCollection term_bindings
        {
            get
            {
                if (term_bindingsField == null)
                {
                    this.term_bindingsField = new TermBindingSetCollection();
                }
                return term_bindingsField;
            }
            set
            {
                this.term_bindingsField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("term_bindings");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("constraint_bindings")]
        [Barcline.Core.MinOccurs("0")]
        [Barcline.Core.MaxOccurs("unbounded")]
        public virtual ConstraintBindingSetCollection constraint_bindings
        {
            get
            {
                if (constraint_bindingsField == null)
                {
                    this.constraint_bindingsField = new ConstraintBindingSetCollection();
                }
                return constraint_bindingsField;
            }
            set
            {
                this.constraint_bindingsField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("constraint_bindings");
            }
        }

        [field: NonSerialized]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
