//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    /// <summary>
    /// Required properties: expression
    /// </summary>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("ASSERTION", Schema = "openehr")]
    public partial class ASSERTION : System.ComponentModel.INotifyPropertyChanged
    {
        
        private string tagField;
        
        private string string_expressionField;
        
        private EXPR_ITEM expressionField;
        
        private ASSERTION_VARIABLECollection variablesField;
        
        [Barcline.Core.MinOccurs("0")]
        [MaxLength(4000)]
        public virtual string tag
        {
            get
            {
                return this.tagField;
            }
            set
            {
                this.tagField = value;
                this.RaisePropertyChanged("tag");
            }
        }
        
        [Barcline.Core.MinOccurs("0")]
        [MaxLength(4000)]
        public virtual string string_expression
        {
            get
            {
                return this.string_expressionField;
            }
            set
            {
                this.string_expressionField = value;
                this.RaisePropertyChanged("string_expression");
            }
        }
        
        [Required()]
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual EXPR_ITEM expression
        {
            get
            {
                return expressionField;
            }
            set
            {
                this.expressionField = value;
                this.RaisePropertyChanged("expression");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("variables")]
        [Barcline.Core.MinOccurs("0")]
        [Barcline.Core.MaxOccurs("unbounded")]
        public virtual ASSERTION_VARIABLECollection variables
        {
            get
            {
                if (variablesField == null)
                {
                    this.variablesField = new ASSERTION_VARIABLECollection();
                }
                return variablesField;
            }
            set
            {
                this.variablesField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("variables");
            }
        }

        [field: NonSerialized]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
