//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("C_DATE_TIME", Schema = "openehr")]
    public partial class C_DATE_TIME : C_PRIMITIVE
    {
        
        private string patternField;
        
        private VALIDITY_KIND timezone_validityField;
        
        private bool timezone_validityFieldSpecified;
        
        private IntervalOfDateTime rangeField;
        
        private DateTime? assumed_valueField;
        
        [MaxLength(4000)]
        public virtual string pattern
        {
            get
            {
                return this.patternField;
            }
            set
            {
                this.patternField = value;
                this.RaisePropertyChanged("pattern");
            }
        }
        
        public virtual VALIDITY_KIND timezone_validity
        {
            get
            {
                return timezone_validityField;
            }
            set
            {
                this.timezone_validityField = value;
                this.RaisePropertyChanged("timezone_validity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool timezone_validitySpecified
        {
            get
            {
                return this.timezone_validityFieldSpecified;
            }
            set
            {
                this.timezone_validityFieldSpecified = value;
                this.RaisePropertyChanged("timezone_validitySpecified");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual IntervalOfDateTime range
        {
            get
            {
                return rangeField;
            }
            set
            {
                this.rangeField = value;
                this.RaisePropertyChanged("range");
            }
        }
        
        public virtual DateTime? assumed_value
        {
            get
            {
                return this.assumed_valueField;
            }
            set
            {
                this.assumed_valueField = value;
                this.RaisePropertyChanged("assumed_value");
            }
        }
    }
}
