//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(C_DURATION))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(C_TIME))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(C_DATE_TIME))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(C_DATE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(C_REAL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(C_INTEGER))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(C_STRING))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(C_BOOLEAN))]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("C_PRIMITIVE", Schema = "openehr")]
    public abstract partial class C_PRIMITIVE : System.ComponentModel.INotifyPropertyChanged
    {
        [field: NonSerialized]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
