//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    /// <summary>
    /// Required properties: units
    /// </summary>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("C_QUANTITY_ITEM", Schema = "openehr")]
    public partial class C_QUANTITY_ITEM : System.ComponentModel.INotifyPropertyChanged
    {
        
        private IntervalOfReal magnitudeField;
        
        private IntervalOfInteger precisionField;
        
        private string unitsField;
        
        [Barcline.Core.MinOccurs("0")]
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual IntervalOfReal magnitude
        {
            get
            {
                return magnitudeField;
            }
            set
            {
                this.magnitudeField = value;
                this.RaisePropertyChanged("magnitude");
            }
        }
        
        [Barcline.Core.MinOccurs("0")]
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual IntervalOfInteger precision
        {
            get
            {
                return precisionField;
            }
            set
            {
                this.precisionField = value;
                this.RaisePropertyChanged("precision");
            }
        }
        
        [Required()]
        [MaxLength(4000)]
        public virtual string units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
                this.RaisePropertyChanged("units");
            }
        }

        [field: NonSerialized]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
