//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("C_REAL", Schema = "openehr")]
    public partial class C_REAL : C_PRIMITIVE
    {
        
        private float[] listField;
        
        private IntervalOfReal rangeField;
        
        private float assumed_valueField;
        
        private bool assumed_valueFieldSpecified;
        
        [System.Xml.Serialization.XmlElementAttribute("list")]
        [NotMapped]
        public virtual float[] list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
                this.RaisePropertyChanged("list");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual IntervalOfReal range
        {
            get
            {
                return rangeField;
            }
            set
            {
                this.rangeField = value;
                this.RaisePropertyChanged("range");
            }
        }
        
        public virtual float assumed_value
        {
            get
            {
                return this.assumed_valueField;
            }
            set
            {
                this.assumed_valueField = value;
                this.RaisePropertyChanged("assumed_value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool assumed_valueSpecified
        {
            get
            {
                return this.assumed_valueFieldSpecified;
            }
            set
            {
                this.assumed_valueFieldSpecified = value;
                this.RaisePropertyChanged("assumed_valueSpecified");
            }
        }
    }
}
