//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("CAPABILITY", Schema = "demographic")]
    public partial class CAPABILITY : LOCATABLE
    {
        
        private ITEM_STRUCTURE credentialsField;
        
        private DV_INTERVAL time_validityField;
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual ITEM_STRUCTURE credentials
        {
            get
            {
                return credentialsField;
            }
            set
            {
                this.credentialsField = value;
                this.RaisePropertyChanged("credentials");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_INTERVAL time_validity
        {
            get
            {
                return time_validityField;
            }
            set
            {
                this.time_validityField = value;
                this.RaisePropertyChanged("time_validity");
            }
        }
    }
}
