//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute("composition", Namespace="http://schemas.openehr.org/v1", IsNullable=false)]
    [Table("COMPOSITION", Schema = "openehr")]
    public partial class COMPOSITION : VERSIONED
    {
        
        private CODE_PHRASE languageField;
        
        private CODE_PHRASE territoryField;
        
        private DV_CODED_TEXT categoryField;
        
        private PARTY_PROXY composerField;
        
        private EVENT_CONTEXT contextField;
        
        private CONTENT_ITEMCollection contentField;
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual CODE_PHRASE language
        {
            get
            {
                return languageField;
            }
            set
            {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual CODE_PHRASE territory
        {
            get
            {
                return territoryField;
            }
            set
            {
                this.territoryField = value;
                this.RaisePropertyChanged("territory");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_CODED_TEXT category
        {
            get
            {
                return categoryField;
            }
            set
            {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual PARTY_PROXY composer
        {
            get
            {
                return composerField;
            }
            set
            {
                this.composerField = value;
                this.RaisePropertyChanged("composer");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual EVENT_CONTEXT context
        {
            get
            {
                return contextField;
            }
            set
            {
                this.contextField = value;
                this.RaisePropertyChanged("context");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("content")]
        public virtual CONTENT_ITEMCollection content
        {
            get
            {
                if (contentField == null)
                {
                    this.contentField = new CONTENT_ITEMCollection();
                }
                return contentField;
            }
            set
            {
                this.contentField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("content");
            }
        }
    }
}
