//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTRY))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CARE_ENTRY))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ACTION))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(INSTRUCTION))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OBSERVATION))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EVALUATION))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ADMIN_ENTRY))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GENERIC_ENTRY))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SECTION))]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("CONTENT_ITEM", Schema = "openehr")]
    public abstract partial class CONTENT_ITEM : LOCATABLE
    {
    }
}
