//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("DV_IDENTIFIER", Schema = "openehr")]
    public partial class DV_IDENTIFIER : DATA_VALUE
    {
        
        private string issuerField;
        
        private string assignerField;
        
        private string idField;
        
        private string typeField;
        
        [MaxLength(4000)]
        public virtual string issuer
        {
            get
            {
                return this.issuerField;
            }
            set
            {
                this.issuerField = value;
                this.RaisePropertyChanged("issuer");
            }
        }
        
        [MaxLength(4000)]
        public virtual string assigner
        {
            get
            {
                return this.assignerField;
            }
            set
            {
                this.assignerField = value;
                this.RaisePropertyChanged("assigner");
            }
        }
        
        [MaxLength(4000)]
        public virtual string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        [MaxLength(4000)]
        public virtual string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
    }
}
