//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("DV_MULTIMEDIA", Schema = "openehr")]
    public partial class DV_MULTIMEDIA : DV_ENCAPSULATED
    {
        
        private string alternate_textField;
        
        private DV_URI uriField;
        
        private byte[] dataField;
        
        private CODE_PHRASE media_typeField;
        
        private CODE_PHRASE compression_algorithmField;
        
        private byte[] integrity_checkField;
        
        private CODE_PHRASE integrity_check_algorithmField;
        
        private int sizeField;
        
        private DV_MULTIMEDIA thumbnailField;
        
        [MaxLength(4000)]
        public virtual string alternate_text
        {
            get
            {
                return this.alternate_textField;
            }
            set
            {
                this.alternate_textField = value;
                this.RaisePropertyChanged("alternate_text");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_URI uri
        {
            get
            {
                return uriField;
            }
            set
            {
                this.uriField = value;
                this.RaisePropertyChanged("uri");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public virtual byte[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual CODE_PHRASE media_type
        {
            get
            {
                return media_typeField;
            }
            set
            {
                this.media_typeField = value;
                this.RaisePropertyChanged("media_type");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual CODE_PHRASE compression_algorithm
        {
            get
            {
                return compression_algorithmField;
            }
            set
            {
                this.compression_algorithmField = value;
                this.RaisePropertyChanged("compression_algorithm");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public virtual byte[] integrity_check
        {
            get
            {
                return this.integrity_checkField;
            }
            set
            {
                this.integrity_checkField = value;
                this.RaisePropertyChanged("integrity_check");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual CODE_PHRASE integrity_check_algorithm
        {
            get
            {
                return integrity_check_algorithmField;
            }
            set
            {
                this.integrity_check_algorithmField = value;
                this.RaisePropertyChanged("integrity_check_algorithm");
            }
        }
        
        public virtual int size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
                this.RaisePropertyChanged("size");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_MULTIMEDIA thumbnail
        {
            get
            {
                return thumbnailField;
            }
            set
            {
                this.thumbnailField = value;
                this.RaisePropertyChanged("thumbnail");
            }
        }
    }
}
