//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_ORDINAL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_QUANTIFIED))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_TEMPORAL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_DATE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_TIME))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_DATE_TIME))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_AMOUNT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_DURATION))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_PROPORTION))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_QUANTITY))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_COUNT))]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("DV_ORDERED", Schema = "openehr")]
    public abstract partial class DV_ORDERED : DATA_VALUE
    {
        
        private DV_INTERVAL normal_rangeField;
        
        private REFERENCE_RANGECollection other_reference_rangesField;
        
        private CODE_PHRASE normal_statusField;
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_INTERVAL normal_range
        {
            get
            {
                return normal_rangeField;
            }
            set
            {
                this.normal_rangeField = value;
                this.RaisePropertyChanged("normal_range");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("other_reference_ranges")]
        public virtual REFERENCE_RANGECollection other_reference_ranges
        {
            get
            {
                if (other_reference_rangesField == null)
                {
                    this.other_reference_rangesField = new REFERENCE_RANGECollection();
                }
                return other_reference_rangesField;
            }
            set
            {
                this.other_reference_rangesField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("other_reference_ranges");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual CODE_PHRASE normal_status
        {
            get
            {
                return normal_statusField;
            }
            set
            {
                this.normal_statusField = value;
                this.RaisePropertyChanged("normal_status");
            }
        }
    }
}
