//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("DV_PROPORTION", Schema = "openehr")]
    public partial class DV_PROPORTION : DV_AMOUNT
    {
        
        private float numeratorField;
        
        private float denominatorField;
        
        private PROPORTION_KIND typeField;
        
        private int precisionField;
        
        public DV_PROPORTION()
        {
            this.precisionField = -1;
        }
        
        public virtual float numerator
        {
            get
            {
                return this.numeratorField;
            }
            set
            {
                this.numeratorField = value;
                this.RaisePropertyChanged("numerator");
            }
        }
        
        public virtual float denominator
        {
            get
            {
                return this.denominatorField;
            }
            set
            {
                this.denominatorField = value;
                this.RaisePropertyChanged("denominator");
            }
        }
        
        public virtual PROPORTION_KIND type
        {
            get
            {
                return typeField;
            }
            set
            {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public virtual int precision
        {
            get
            {
                return this.precisionField;
            }
            set
            {
                this.precisionField = value;
                this.RaisePropertyChanged("precision");
            }
        }
    }
}
