//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_TEMPORAL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_DATE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_TIME))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_DATE_TIME))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_AMOUNT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_DURATION))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_PROPORTION))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_QUANTITY))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DV_COUNT))]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("DV_QUANTIFIED", Schema = "openehr")]
    public abstract partial class DV_QUANTIFIED : DV_ORDERED
    {
        
        private string magnitude_statusField;
        
        [MaxLength(4000)]
        public virtual string magnitude_status
        {
            get
            {
                return this.magnitude_statusField;
            }
            set
            {
                this.magnitude_statusField = value;
                this.RaisePropertyChanged("magnitude_status");
            }
        }
    }
}
