//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CARE_ENTRY))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ACTION))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(INSTRUCTION))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OBSERVATION))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EVALUATION))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ADMIN_ENTRY))]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("ENTRY", Schema = "openehr")]
    public abstract partial class ENTRY : CONTENT_ITEM
    {
        
        private CODE_PHRASE languageField;
        
        private CODE_PHRASE encodingField;
        
        private PARTY_PROXY subjectField;
        
        private PARTY_PROXY providerField;
        
        private PARTICIPATIONCollection other_participationsField;
        
        private OBJECT_REF work_flow_idField;
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual CODE_PHRASE language
        {
            get
            {
                return languageField;
            }
            set
            {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual CODE_PHRASE encoding
        {
            get
            {
                return encodingField;
            }
            set
            {
                this.encodingField = value;
                this.RaisePropertyChanged("encoding");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual PARTY_PROXY subject
        {
            get
            {
                return subjectField;
            }
            set
            {
                this.subjectField = value;
                this.RaisePropertyChanged("subject");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual PARTY_PROXY provider
        {
            get
            {
                return providerField;
            }
            set
            {
                this.providerField = value;
                this.RaisePropertyChanged("provider");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("other_participations")]
        public virtual PARTICIPATIONCollection other_participations
        {
            get
            {
                if (other_participationsField == null)
                {
                    this.other_participationsField = new PARTICIPATIONCollection();
                }
                return other_participationsField;
            }
            set
            {
                this.other_participationsField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("other_participations");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual OBJECT_REF work_flow_id
        {
            get
            {
                return work_flow_idField;
            }
            set
            {
                this.work_flow_idField = value;
                this.RaisePropertyChanged("work_flow_id");
            }
        }
    }
}
