//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    /// <summary>
    /// Required properties: setting, start_time
    /// </summary>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("EVENT_CONTEXT", Schema = "openehr")]
    public partial class EVENT_CONTEXT : System.ComponentModel.INotifyPropertyChanged
    {
        
        private DV_DATE_TIME start_timeField;
        
        private DV_DATE_TIME end_timeField;
        
        private string locationField;
        
        private DV_CODED_TEXT settingField;
        
        private ITEM_STRUCTURE other_contextField;
        
        private PARTY_IDENTIFIED health_care_facilityField;
        
        private PARTICIPATIONCollection participationsField;
        
        [Required()]
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_DATE_TIME start_time
        {
            get
            {
                return start_timeField;
            }
            set
            {
                this.start_timeField = value;
                this.RaisePropertyChanged("start_time");
            }
        }
        
        [Barcline.Core.MinOccurs("0")]
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_DATE_TIME end_time
        {
            get
            {
                return end_timeField;
            }
            set
            {
                this.end_timeField = value;
                this.RaisePropertyChanged("end_time");
            }
        }
        
        [Barcline.Core.MinOccurs("0")]
        [MaxLength(4000)]
        public virtual string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        [Required()]
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_CODED_TEXT setting
        {
            get
            {
                return settingField;
            }
            set
            {
                this.settingField = value;
                this.RaisePropertyChanged("setting");
            }
        }
        
        [Barcline.Core.MinOccurs("0")]
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual ITEM_STRUCTURE other_context
        {
            get
            {
                return other_contextField;
            }
            set
            {
                this.other_contextField = value;
                this.RaisePropertyChanged("other_context");
            }
        }
        
        [Barcline.Core.MinOccurs("0")]
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual PARTY_IDENTIFIED health_care_facility
        {
            get
            {
                return health_care_facilityField;
            }
            set
            {
                this.health_care_facilityField = value;
                this.RaisePropertyChanged("health_care_facility");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("participations")]
        [Barcline.Core.MinOccurs("0")]
        [Barcline.Core.MaxOccurs("unbounded")]
        public virtual PARTICIPATIONCollection participations
        {
            get
            {
                if (participationsField == null)
                {
                    this.participationsField = new PARTICIPATIONCollection();
                }
                return participationsField;
            }
            set
            {
                this.participationsField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("participations");
            }
        }

        [field: NonSerialized]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
