//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    /// <summary>
    /// Required properties: type
    /// </summary>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EXPR_OPERATOR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EXPR_BINARY_OPERATOR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EXPR_UNARY_OPERATOR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EXPR_LEAF))]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("EXPR_ITEM", Schema = "openehr")]
    public abstract partial class EXPR_ITEM : System.ComponentModel.INotifyPropertyChanged
    {
        
        private string typeField;
        
        [Required()]
        [MaxLength(4000)]
        public virtual string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }

        [field: NonSerialized]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
