//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("EXPR_BINARY_OPERATOR", Schema = "openehr")]
    public partial class EXPR_BINARY_OPERATOR : EXPR_OPERATOR
    {
        
        private EXPR_ITEM left_operandField;
        
        private EXPR_ITEM right_operandField;
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual EXPR_ITEM left_operand
        {
            get
            {
                return left_operandField;
            }
            set
            {
                this.left_operandField = value;
                this.RaisePropertyChanged("left_operand");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual EXPR_ITEM right_operand
        {
            get
            {
                return right_operandField;
            }
            set
            {
                this.right_operandField = value;
                this.RaisePropertyChanged("right_operand");
            }
        }
    }
}
