//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    /// <summary>
    /// Required properties: include_all_versions, includes_data, includes_revision_history
    /// </summary>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("EXTRACT_VERSION_SPEC", Schema = "openehr")]
    public partial class EXTRACT_VERSION_SPEC : System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool include_all_versionsField;
        
        private DV_INTERVAL commit_time_intervalField;
        
        private bool includes_revision_historyField;
        
        private bool includes_dataField;
        
        [Required()]
        public virtual bool include_all_versions
        {
            get
            {
                return this.include_all_versionsField;
            }
            set
            {
                this.include_all_versionsField = value;
                this.RaisePropertyChanged("include_all_versions");
            }
        }
        
        [Barcline.Core.MinOccurs("0")]
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_INTERVAL commit_time_interval
        {
            get
            {
                return commit_time_intervalField;
            }
            set
            {
                this.commit_time_intervalField = value;
                this.RaisePropertyChanged("commit_time_interval");
            }
        }
        
        [Required()]
        public virtual bool includes_revision_history
        {
            get
            {
                return this.includes_revision_historyField;
            }
            set
            {
                this.includes_revision_historyField = value;
                this.RaisePropertyChanged("includes_revision_history");
            }
        }
        
        [Required()]
        public virtual bool includes_data
        {
            get
            {
                return this.includes_dataField;
            }
            set
            {
                this.includes_dataField = value;
                this.RaisePropertyChanged("includes_data");
            }
        }

        [field: NonSerialized]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
