//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    /// <summary>
    /// Required properties: persist_in_server, send_changes_only
    /// </summary>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("EXTRACT_UPDATE_SPEC", Schema = "openehr")]
    public partial class EXTRACT_UPDATE_SPEC : System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool persist_in_serverField;
        
        private DV_INTERVAL repeat_periodField;
        
        private string[] trigger_eventsField;
        
        private bool send_changes_onlyField;
        
        [Required()]
        public virtual bool persist_in_server
        {
            get
            {
                return this.persist_in_serverField;
            }
            set
            {
                this.persist_in_serverField = value;
                this.RaisePropertyChanged("persist_in_server");
            }
        }
        
        [Barcline.Core.MinOccurs("0")]
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_INTERVAL repeat_period
        {
            get
            {
                return repeat_periodField;
            }
            set
            {
                this.repeat_periodField = value;
                this.RaisePropertyChanged("repeat_period");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("trigger_events")]
        [Barcline.Core.MinOccurs("0")]
        [Barcline.Core.MaxOccurs("unbounded")]
        [MaxLength(4000)]
        public virtual string[] trigger_events
        {
            get
            {
                return this.trigger_eventsField;
            }
            set
            {
                this.trigger_eventsField = value;
                this.RaisePropertyChanged("trigger_events");
            }
        }
        
        [Required()]
        public virtual bool send_changes_only
        {
            get
            {
                return this.send_changes_onlyField;
            }
            set
            {
                this.send_changes_onlyField = value;
                this.RaisePropertyChanged("send_changes_only");
            }
        }

        [field: NonSerialized]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
