//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute("extract", Namespace="http://schemas.openehr.org/v1", IsNullable=false)]
    [Table("EXTRACT", Schema = "openehr")]
    public partial class EXTRACT : LOCATABLE
    {
        
        private OBJECT_REF request_idField;
        
        private DV_DATE_TIME time_createdField;
        
        private HIER_OBJECT_ID system_idField;
        
        private PARTICIPATIONCollection participationsField;
        
        private long sequence_nrField;
        
        private EXTRACT_CHAPTERCollection chaptersField;
        
        private EXTRACT_SPEC specificationField;
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual OBJECT_REF request_id
        {
            get
            {
                return request_idField;
            }
            set
            {
                this.request_idField = value;
                this.RaisePropertyChanged("request_id");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_DATE_TIME time_created
        {
            get
            {
                return time_createdField;
            }
            set
            {
                this.time_createdField = value;
                this.RaisePropertyChanged("time_created");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual HIER_OBJECT_ID system_id
        {
            get
            {
                return system_idField;
            }
            set
            {
                this.system_idField = value;
                this.RaisePropertyChanged("system_id");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("participations")]
        public virtual PARTICIPATIONCollection participations
        {
            get
            {
                if (participationsField == null)
                {
                    this.participationsField = new PARTICIPATIONCollection();
                }
                return participationsField;
            }
            set
            {
                this.participationsField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("participations");
            }
        }
        
        public virtual long sequence_nr
        {
            get
            {
                return this.sequence_nrField;
            }
            set
            {
                this.sequence_nrField = value;
                this.RaisePropertyChanged("sequence_nr");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("chapters")]
        public virtual EXTRACT_CHAPTERCollection chapters
        {
            get
            {
                if (chaptersField == null)
                {
                    this.chaptersField = new EXTRACT_CHAPTERCollection();
                }
                return chaptersField;
            }
            set
            {
                this.chaptersField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("chapters");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual EXTRACT_SPEC specification
        {
            get
            {
                return specificationField;
            }
            set
            {
                this.specificationField = value;
                this.RaisePropertyChanged("specification");
            }
        }
    }
}
