//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("HISTORY", Schema = "openehr")]
    public partial class HISTORY : LOCATABLE
    {
        
        private DV_DATE_TIME originField;
        
        private DV_DURATION periodField;
        
        private DV_DURATION durationField;
        
        private EVENTCollection eventsField;
        
        private ITEM_STRUCTURE summaryField;
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_DATE_TIME origin
        {
            get
            {
                return originField;
            }
            set
            {
                this.originField = value;
                this.RaisePropertyChanged("origin");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_DURATION period
        {
            get
            {
                return periodField;
            }
            set
            {
                this.periodField = value;
                this.RaisePropertyChanged("period");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_DURATION duration
        {
            get
            {
                return durationField;
            }
            set
            {
                this.durationField = value;
                this.RaisePropertyChanged("duration");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("events")]
        public virtual EVENTCollection events
        {
            get
            {
                if (eventsField == null)
                {
                    this.eventsField = new EVENTCollection();
                }
                return eventsField;
            }
            set
            {
                this.eventsField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("events");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual ITEM_STRUCTURE summary
        {
            get
            {
                return summaryField;
            }
            set
            {
                this.summaryField = value;
                this.RaisePropertyChanged("summary");
            }
        }
    }
}
