//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("INSTRUCTION", Schema = "openehr")]
    public partial class INSTRUCTION : CARE_ENTRY
    {
        
        private DV_TEXT narrativeField;
        
        private DV_DATE_TIME expiry_timeField;
        
        private DV_PARSABLE wf_definitionField;
        
        private ACTIVITYCollection activitiesField;
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_TEXT narrative
        {
            get
            {
                return narrativeField;
            }
            set
            {
                this.narrativeField = value;
                this.RaisePropertyChanged("narrative");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_DATE_TIME expiry_time
        {
            get
            {
                return expiry_timeField;
            }
            set
            {
                this.expiry_timeField = value;
                this.RaisePropertyChanged("expiry_time");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_PARSABLE wf_definition
        {
            get
            {
                return wf_definitionField;
            }
            set
            {
                this.wf_definitionField = value;
                this.RaisePropertyChanged("wf_definition");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("activities")]
        public virtual ACTIVITYCollection activities
        {
            get
            {
                if (activitiesField == null)
                {
                    this.activitiesField = new ACTIVITYCollection();
                }
                return activitiesField;
            }
            set
            {
                this.activitiesField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("activities");
            }
        }
    }
}
