//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    /// <summary>
    /// Required properties: activity_id, instruction_id
    /// </summary>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("INSTRUCTION_DETAILS", Schema = "openehr")]
    public partial class INSTRUCTION_DETAILS : System.ComponentModel.INotifyPropertyChanged
    {
        
        private LOCATABLE_REF instruction_idField;
        
        private string activity_idField;
        
        private ITEM_STRUCTURE wf_detailsField;
        
        [Required()]
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual LOCATABLE_REF instruction_id
        {
            get
            {
                return instruction_idField;
            }
            set
            {
                this.instruction_idField = value;
                this.RaisePropertyChanged("instruction_id");
            }
        }
        
        [Required()]
        [MaxLength(4000)]
        public virtual string activity_id
        {
            get
            {
                return this.activity_idField;
            }
            set
            {
                this.activity_idField = value;
                this.RaisePropertyChanged("activity_id");
            }
        }
        
        [Barcline.Core.MinOccurs("0")]
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual ITEM_STRUCTURE wf_details
        {
            get
            {
                return wf_detailsField;
            }
            set
            {
                this.wf_detailsField = value;
                this.RaisePropertyChanged("wf_details");
            }
        }

        [field: NonSerialized]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
