//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("IntervalOfReal", Schema = "openehr")]
    public partial class IntervalOfReal : Interval
    {
        
        private float lowerField;
        
        private bool lowerFieldSpecified;
        
        private float upperField;
        
        private bool upperFieldSpecified;
        
        public virtual float lower
        {
            get
            {
                return this.lowerField;
            }
            set
            {
                this.lowerField = value;
                this.RaisePropertyChanged("lower");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool lowerSpecified
        {
            get
            {
                return this.lowerFieldSpecified;
            }
            set
            {
                this.lowerFieldSpecified = value;
                this.RaisePropertyChanged("lowerSpecified");
            }
        }
        
        public virtual float upper
        {
            get
            {
                return this.upperField;
            }
            set
            {
                this.upperField = value;
                this.RaisePropertyChanged("upper");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool upperSpecified
        {
            get
            {
                return this.upperFieldSpecified;
            }
            set
            {
                this.upperFieldSpecified = value;
                this.RaisePropertyChanged("upperSpecified");
            }
        }
    }
}
