//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("NON_TERMINAL_STATE", Schema = "openehr")]
    public partial class NON_TERMINAL_STATE : STATE
    {
        
        private TRANSITIONCollection transitionsField;
        
        [System.Xml.Serialization.XmlElementAttribute("transitions")]
        public virtual TRANSITIONCollection transitions
        {
            get
            {
                if (transitionsField == null)
                {
                    this.transitionsField = new TRANSITIONCollection();
                }
                return transitionsField;
            }
            set
            {
                this.transitionsField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("transitions");
            }
        }
    }
}
