//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    /// <summary>
    /// Required properties: id, namespace, type
    /// </summary>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LOCATABLE_REF))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ACCESS_GROUP_REF))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PARTY_REF))]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("OBJECT_REF", Schema = "openehr")]
    public partial class OBJECT_REF : System.ComponentModel.INotifyPropertyChanged
    {
        
        private OBJECT_ID idField;
        
        private string namespaceField;
        
        private string typeField;
        
        [Required()]
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual OBJECT_ID id
        {
            get
            {
                return idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        [Required()]
        [MaxLength(4000)]
        public virtual string @namespace
        {
            get
            {
                return this.namespaceField;
            }
            set
            {
                this.namespaceField = value;
                this.RaisePropertyChanged("namespace");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        [Required()]
        [MaxLength(4000)]
        public virtual string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }

        [field: NonSerialized]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
