//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("ORIGINAL_VERSION", Schema = "openehr")]
    public partial class ORIGINAL_VERSION : VERSION
    {
        
        private OBJECT_VERSION_ID uidField;
        
        private VERSIONED dataField;
        
        private OBJECT_VERSION_ID preceding_version_uidField;
        
        private OBJECT_VERSION_IDCollection other_input_version_uidsField;
        
        private ATTESTATIONCollection attestationsField;
        
        private DV_CODED_TEXT lifecycle_stateField;
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual OBJECT_VERSION_ID uid
        {
            get
            {
                return uidField;
            }
            set
            {
                this.uidField = value;
                this.RaisePropertyChanged("uid");
            }
        }
        
        public virtual VERSIONED data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual OBJECT_VERSION_ID preceding_version_uid
        {
            get
            {
                return preceding_version_uidField;
            }
            set
            {
                this.preceding_version_uidField = value;
                this.RaisePropertyChanged("preceding_version_uid");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("other_input_version_uids")]
        public virtual OBJECT_VERSION_IDCollection other_input_version_uids
        {
            get
            {
                if (other_input_version_uidsField == null)
                {
                    this.other_input_version_uidsField = new OBJECT_VERSION_IDCollection();
                }
                return other_input_version_uidsField;
            }
            set
            {
                this.other_input_version_uidsField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("other_input_version_uids");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("attestations")]
        public virtual ATTESTATIONCollection attestations
        {
            get
            {
                if (attestationsField == null)
                {
                    this.attestationsField = new ATTESTATIONCollection();
                }
                return attestationsField;
            }
            set
            {
                this.attestationsField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("attestations");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_CODED_TEXT lifecycle_state
        {
            get
            {
                return lifecycle_stateField;
            }
            set
            {
                this.lifecycle_stateField = value;
                this.RaisePropertyChanged("lifecycle_state");
            }
        }
    }
}
