//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    /// <summary>
    /// Required properties: match, target
    /// </summary>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("TERM_MAPPING", Schema = "openehr")]
    public partial class TERM_MAPPING : System.ComponentModel.INotifyPropertyChanged
    {
        
        private string matchField;
        
        private DV_CODED_TEXT purposeField;
        
        private CODE_PHRASE targetField;
        
        public TERM_MAPPING()
        {
            this.matchField = "?";
        }
        
        [Required()]
        [MaxLength(4000)]
        public virtual string match
        {
            get
            {
                return this.matchField;
            }
            set
            {
                this.matchField = value;
                this.RaisePropertyChanged("match");
            }
        }
        
        [Barcline.Core.MinOccurs("0")]
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual DV_CODED_TEXT purpose
        {
            get
            {
                return purposeField;
            }
            set
            {
                this.purposeField = value;
                this.RaisePropertyChanged("purpose");
            }
        }
        
        [Required()]
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual CODE_PHRASE target
        {
            get
            {
                return targetField;
            }
            set
            {
                this.targetField = value;
                this.RaisePropertyChanged("target");
            }
        }

        [field: NonSerialized]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
