//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ORGANISATION))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AGENT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GROUP))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PERSON))]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("ACTOR", Schema = "demographic")]
    public abstract partial class ACTOR : PARTY
    {
        
        private PARTY_REFCollection rolesField;
        
        private DV_TEXTCollection languagesField;
        
        [System.Xml.Serialization.XmlElementAttribute("roles")]
        public virtual PARTY_REFCollection roles
        {
            get
            {
                if (rolesField == null)
                {
                    this.rolesField = new PARTY_REFCollection();
                }
                return rolesField;
            }
            set
            {
                this.rolesField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("roles");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("languages")]
        public virtual DV_TEXTCollection languages
        {
            get
            {
                if (languagesField == null)
                {
                    this.languagesField = new DV_TEXTCollection();
                }
                return languagesField;
            }
            set
            {
                this.languagesField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("languages");
            }
        }
    }
}
