//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.OpenEhr.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ACTOR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ORGANISATION))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AGENT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GROUP))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PERSON))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ROLE))]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.openehr.org/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.openehr.org/v1", IsNullable=true)]
    [Table("PARTY", Schema = "demographic")]
    public partial class PARTY : VERSIONED
    {
        
        private PARTY_IDENTITYCollection identifiersField;
        
        private CONTACTCollection contactsField;
        
        private PARTY_RELATIONSHIPCollection relationshipsField;
        
        private LOCATABLE_REFCollection reverse_relationshipsField;
        
        private ITEM_STRUCTURE detailsField;
        
        [System.Xml.Serialization.XmlElementAttribute("identifiers")]
        public virtual PARTY_IDENTITYCollection identifiers
        {
            get
            {
                if (identifiersField == null)
                {
                    this.identifiersField = new PARTY_IDENTITYCollection();
                }
                return identifiersField;
            }
            set
            {
                this.identifiersField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("identifiers");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("contacts")]
        public virtual CONTACTCollection contacts
        {
            get
            {
                if (this.contactsField == null)
                    this.contactsField = new CONTACTCollection();
                return this.contactsField;
            }
            set
            {
                this.contactsField = value;
                this.RaisePropertyChanged("contacts");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("relationships")]
        public virtual PARTY_RELATIONSHIPCollection relationships
        {
            get
            {
                if (relationshipsField == null)
                {
                    this.relationshipsField = new PARTY_RELATIONSHIPCollection();
                }
                return relationshipsField;
            }
            set
            {
                this.relationshipsField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("relationships");
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("reverse_relationships")]
        public virtual LOCATABLE_REFCollection reverse_relationships
        {
            get
            {
                if (reverse_relationshipsField == null)
                {
                    this.reverse_relationshipsField = new LOCATABLE_REFCollection();
                }
                return reverse_relationshipsField;
            }
            set
            {
                this.reverse_relationshipsField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("reverse_relationships");
            }
        }
        
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual ITEM_STRUCTURE details
        {
            get
            {
                return detailsField;
            }
            set
            {
                this.detailsField = value;
                this.RaisePropertyChanged("details");
            }
        }
    }
}
