//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.Hl7.Cda
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XsdShell", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:v3")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:v3", IsNullable=false)]
    public enum ApplicationMediaType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/dicom")]
        applicationdicom,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/msword")]
        applicationmsword,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/pdf")]
        applicationpdf,
    }
}
