//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.Hl7.Cda
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(POCD_MT000040InfrastructureRoottypeId))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XsdShell", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:v3")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:v3", IsNullable=true)]
    public partial class II : ANY
    {
        
        private string rootField;
        
        private string extensionField;
        
        private string assigningAuthorityNameField;
        
        private bool displayableField;
        
        private bool displayableFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual string root
        {
            get
            {
                return this.rootField;
            }
            set
            {
                this.rootField = value;
                this.RaisePropertyChanged("root");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual string extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
                this.RaisePropertyChanged("extension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual string assigningAuthorityName
        {
            get
            {
                return this.assigningAuthorityNameField;
            }
            set
            {
                this.assigningAuthorityNameField = value;
                this.RaisePropertyChanged("assigningAuthorityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual bool displayable
        {
            get
            {
                return this.displayableField;
            }
            set
            {
                this.displayableField = value;
                this.RaisePropertyChanged("displayable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool displayableSpecified
        {
            get
            {
                return this.displayableFieldSpecified;
            }
            set
            {
                this.displayableFieldSpecified = value;
                this.RaisePropertyChanged("displayableSpecified");
            }
        }
    }
}
