//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.Hl7.Cda
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XsdShell", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="POCD_MT000040.RegionOfInterest", Namespace="urn:hl7-org:v3")]
    public partial class POCD_MT000040RegionOfInterest : CdaObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        private CSCollection realmCodeField;
        
        private POCD_MT000040InfrastructureRoottypeId typeIdField;
        
        private IICollection templateIdField;
        
        private IICollection idField;
        
        private CS codeField;
        
        private POCD_MT000040RegionOfInterestvalueCollection valueField;
        
        private POCD_MT000040Subject subjectField;
        
        private POCD_MT000040SpecimenCollection specimenField;
        
        private POCD_MT000040Performer2Collection performerField;
        
        private POCD_MT000040AuthorCollection authorField;
        
        private POCD_MT000040Informant12Collection informantField;
        
        private POCD_MT000040Participant2Collection participantField;
        
        private POCD_MT000040EntryRelationshipCollection entryRelationshipField;
        
        private POCD_MT000040ReferenceCollection referenceField;
        
        private POCD_MT000040PreconditionCollection preconditionField;
        
        private string idField1;
        
        private string nullFlavorField;
        
        private string classCodeField;
        
        private string moodCodeField;
        
        public POCD_MT000040RegionOfInterest()
        {
            this.classCodeField = "ROIOVL";
            this.moodCodeField = "EVN";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("realmCode")]
        public virtual CSCollection realmCode
        {
            get
            {
                if (realmCodeField == null)
                {
                    this.realmCodeField = new CSCollection();
                }
                return realmCodeField;
            }
            set
            {
                this.realmCodeField = value;
                this.RaisePropertyChanged("realmCode");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual POCD_MT000040InfrastructureRoottypeId typeId
        {
            get
            {
                return typeIdField;
            }
            set
            {
                this.typeIdField = value;
                this.RaisePropertyChanged("typeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("templateId")]
        public virtual IICollection templateId
        {
            get
            {
                if (templateIdField == null)
                {
                    this.templateIdField = new IICollection();
                }
                return templateIdField;
            }
            set
            {
                this.templateIdField = value;
                this.RaisePropertyChanged("templateId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id")]
        public virtual IICollection id
        {
            get
            {
                if (idField == null)
                {
                    this.idField = new IICollection();
                }
                return idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual CS code
        {
            get
            {
                return codeField;
            }
            set
            {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public virtual POCD_MT000040RegionOfInterestvalueCollection value
        {
            get
            {
                if (valueField == null)
                {
                    this.valueField = new POCD_MT000040RegionOfInterestvalueCollection();
                }
                return valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual POCD_MT000040Subject subject
        {
            get
            {
                return subjectField;
            }
            set
            {
                this.subjectField = value;
                this.RaisePropertyChanged("subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("specimen")]
        public virtual POCD_MT000040SpecimenCollection specimen
        {
            get
            {
                if (specimenField == null)
                {
                    this.specimenField = new POCD_MT000040SpecimenCollection();
                }
                return specimenField;
            }
            set
            {
                this.specimenField = value;
                this.RaisePropertyChanged("specimen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("performer")]
        public virtual POCD_MT000040Performer2Collection performer
        {
            get
            {
                if (performerField == null)
                {
                    this.performerField = new POCD_MT000040Performer2Collection();
                }
                return performerField;
            }
            set
            {
                this.performerField = value;
                this.RaisePropertyChanged("performer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("author")]
        public virtual POCD_MT000040AuthorCollection author
        {
            get
            {
                if (authorField == null)
                {
                    this.authorField = new POCD_MT000040AuthorCollection();
                }
                return authorField;
            }
            set
            {
                this.authorField = value;
                this.RaisePropertyChanged("author");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("informant")]
        public virtual POCD_MT000040Informant12Collection informant
        {
            get
            {
                if (informantField == null)
                {
                    this.informantField = new POCD_MT000040Informant12Collection();
                }
                return informantField;
            }
            set
            {
                this.informantField = value;
                this.RaisePropertyChanged("informant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("participant")]
        public virtual POCD_MT000040Participant2Collection participant
        {
            get
            {
                if (participantField == null)
                {
                    this.participantField = new POCD_MT000040Participant2Collection();
                }
                return participantField;
            }
            set
            {
                this.participantField = value;
                this.RaisePropertyChanged("participant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entryRelationship")]
        public virtual POCD_MT000040EntryRelationshipCollection entryRelationship
        {
            get
            {
                if (entryRelationshipField == null)
                {
                    this.entryRelationshipField = new POCD_MT000040EntryRelationshipCollection();
                }
                return entryRelationshipField;
            }
            set
            {
                this.entryRelationshipField = value;
                this.RaisePropertyChanged("entryRelationship");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reference")]
        public virtual POCD_MT000040ReferenceCollection reference
        {
            get
            {
                if (referenceField == null)
                {
                    this.referenceField = new POCD_MT000040ReferenceCollection();
                }
                return referenceField;
            }
            set
            {
                this.referenceField = value;
                this.RaisePropertyChanged("reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("precondition")]
        public virtual POCD_MT000040PreconditionCollection precondition
        {
            get
            {
                if (preconditionField == null)
                {
                    this.preconditionField = new POCD_MT000040PreconditionCollection();
                }
                return preconditionField;
            }
            set
            {
                this.preconditionField = value;
                this.RaisePropertyChanged("precondition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public virtual string ID
        {
            get
            {
                return this.idField1;
            }
            set
            {
                this.idField1 = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual string nullFlavor
        {
            get
            {
                return this.nullFlavorField;
            }
            set
            {
                this.nullFlavorField = value;
                this.RaisePropertyChanged("nullFlavor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual string classCode
        {
            get
            {
                return this.classCodeField;
            }
            set
            {
                this.classCodeField = value;
                this.RaisePropertyChanged("classCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual string moodCode
        {
            get
            {
                return this.moodCodeField;
            }
            set
            {
                this.moodCodeField = value;
                this.RaisePropertyChanged("moodCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
