//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.Hl7.Cda
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XsdShell", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="POCD_MT000040.Observation", Namespace="urn:hl7-org:v3")]
    [System.Xml.Serialization.XmlRootAttribute("POCD_MT000040.Observation", Namespace="urn:hl7-org:v3", IsNullable=true)]
    public partial class POCD_MT000040Observation : CdaObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        private CSCollection realmCodeField;
        
        private POCD_MT000040InfrastructureRoottypeId typeIdField;
        
        private IICollection templateIdField;
        
        private IICollection idField;
        
        private CD codeField;
        
        private ST derivationExprField;
        
        private ED textField;
        
        private CS statusCodeField;
        
        private IVL_TS effectiveTimeField;
        
        private CE priorityCodeField;
        
        private IVL_INT repeatNumberField;
        
        private CS languageCodeField;
        
        private ANYCollection valueField;
        
        private CECollection interpretationCodeField;
        
        private CECollection methodCodeField;
        
        private CDCollection targetSiteCodeField;
        
        private POCD_MT000040Subject subjectField;
        
        private POCD_MT000040SpecimenCollection specimenField;
        
        private POCD_MT000040Performer2Collection performerField;
        
        private POCD_MT000040AuthorCollection authorField;
        
        private POCD_MT000040Informant12Collection informantField;
        
        private POCD_MT000040Participant2Collection participantField;
        
        private POCD_MT000040EntryRelationshipCollection entryRelationshipField;
        
        private POCD_MT000040ReferenceCollection referenceField;
        
        private POCD_MT000040PreconditionCollection preconditionField;
        
        private POCD_MT000040ReferenceRangeCollection referenceRangeField;
        
        private string nullFlavorField;
        
        private string classCodeField;
        
        private x_ActMoodDocumentObservation moodCodeField;
        
        private bool negationIndField;
        
        private bool negationIndFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("realmCode")]
        public virtual CSCollection realmCode
        {
            get
            {
                if (realmCodeField == null)
                {
                    this.realmCodeField = new CSCollection();
                }
                return realmCodeField;
            }
            set
            {
                this.realmCodeField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("realmCode");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual POCD_MT000040InfrastructureRoottypeId typeId
        {
            get
            {
                return typeIdField;
            }
            set
            {
                this.typeIdField = value;
                this.RaisePropertyChanged("typeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("templateId")]
        public virtual IICollection templateId
        {
            get
            {
                if (templateIdField == null)
                {
                    this.templateIdField = new IICollection();
                }
                return templateIdField;
            }
            set
            {
                this.templateIdField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("templateId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id")]
        public virtual IICollection id
        {
            get
            {
                if (idField == null)
                {
                    this.idField = new IICollection();
                }
                return idField;
            }
            set
            {
                this.idField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual CD code
        {
            get
            {
                return codeField;
            }
            set
            {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual ST derivationExpr
        {
            get
            {
                return derivationExprField;
            }
            set
            {
                this.derivationExprField = value;
                this.RaisePropertyChanged("derivationExpr");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual ED text
        {
            get
            {
                return textField;
            }
            set
            {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual CS statusCode
        {
            get
            {
                return statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual IVL_TS effectiveTime
        {
            get
            {
                return effectiveTimeField;
            }
            set
            {
                this.effectiveTimeField = value;
                this.RaisePropertyChanged("effectiveTime");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual CE priorityCode
        {
            get
            {
                return priorityCodeField;
            }
            set
            {
                this.priorityCodeField = value;
                this.RaisePropertyChanged("priorityCode");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual IVL_INT repeatNumber
        {
            get
            {
                return repeatNumberField;
            }
            set
            {
                this.repeatNumberField = value;
                this.RaisePropertyChanged("repeatNumber");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual CS languageCode
        {
            get
            {
                return languageCodeField;
            }
            set
            {
                this.languageCodeField = value;
                this.RaisePropertyChanged("languageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public virtual ANYCollection value
        {
            get
            {
                if (valueField == null)
                {
                    this.valueField = new ANYCollection();
                }
                return valueField;
            }
            set
            {
                this.valueField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("interpretationCode")]
        public virtual CECollection interpretationCode
        {
            get
            {
                if (interpretationCodeField == null)
                {
                    this.interpretationCodeField = new CECollection();
                }
                return interpretationCodeField;
            }
            set
            {
                this.interpretationCodeField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("interpretationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("methodCode")]
        public virtual CECollection methodCode
        {
            get
            {
                if (methodCodeField == null)
                {
                    this.methodCodeField = new CECollection();
                }
                return methodCodeField;
            }
            set
            {
                this.methodCodeField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("methodCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("targetSiteCode")]
        public virtual CDCollection targetSiteCode
        {
            get
            {
                if (targetSiteCodeField == null)
                {
                    this.targetSiteCodeField = new CDCollection();
                }
                return targetSiteCodeField;
            }
            set
            {
                this.targetSiteCodeField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("targetSiteCode");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual POCD_MT000040Subject subject
        {
            get
            {
                return subjectField;
            }
            set
            {
                this.subjectField = value;
                this.RaisePropertyChanged("subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("specimen")]
        public virtual POCD_MT000040SpecimenCollection specimen
        {
            get
            {
                if (specimenField == null)
                {
                    this.specimenField = new POCD_MT000040SpecimenCollection();
                }
                return specimenField;
            }
            set
            {
                this.specimenField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("specimen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("performer")]
        public virtual POCD_MT000040Performer2Collection performer
        {
            get
            {
                if (performerField == null)
                {
                    this.performerField = new POCD_MT000040Performer2Collection();
                }
                return performerField;
            }
            set
            {
                this.performerField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("performer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("author")]
        public virtual POCD_MT000040AuthorCollection author
        {
            get
            {
                if (authorField == null)
                {
                    this.authorField = new POCD_MT000040AuthorCollection();
                }
                return authorField;
            }
            set
            {
                this.authorField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("author");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("informant")]
        public virtual POCD_MT000040Informant12Collection informant
        {
            get
            {
                if (informantField == null)
                {
                    this.informantField = new POCD_MT000040Informant12Collection();
                }
                return informantField;
            }
            set
            {
                this.informantField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("informant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("participant")]
        public virtual POCD_MT000040Participant2Collection participant
        {
            get
            {
                if (participantField == null)
                {
                    this.participantField = new POCD_MT000040Participant2Collection();
                }
                return participantField;
            }
            set
            {
                this.participantField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("participant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entryRelationship")]
        public virtual POCD_MT000040EntryRelationshipCollection entryRelationship
        {
            get
            {
                if (entryRelationshipField == null)
                {
                    this.entryRelationshipField = new POCD_MT000040EntryRelationshipCollection();
                }
                return entryRelationshipField;
            }
            set
            {
                this.entryRelationshipField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("entryRelationship");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reference")]
        public virtual POCD_MT000040ReferenceCollection reference
        {
            get
            {
                if (referenceField == null)
                {
                    this.referenceField = new POCD_MT000040ReferenceCollection();
                }
                return referenceField;
            }
            set
            {
                this.referenceField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("precondition")]
        public virtual POCD_MT000040PreconditionCollection precondition
        {
            get
            {
                if (preconditionField == null)
                {
                    this.preconditionField = new POCD_MT000040PreconditionCollection();
                }
                return preconditionField;
            }
            set
            {
                this.preconditionField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("precondition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referenceRange")]
        public virtual POCD_MT000040ReferenceRangeCollection referenceRange
        {
            get
            {
                if (referenceRangeField == null)
                {
                    this.referenceRangeField = new POCD_MT000040ReferenceRangeCollection();
                }
                return referenceRangeField;
            }
            set
            {
                this.referenceRangeField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("referenceRange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual string nullFlavor
        {
            get
            {
                return this.nullFlavorField;
            }
            set
            {
                this.nullFlavorField = value;
                this.RaisePropertyChanged("nullFlavor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual string classCode
        {
            get
            {
                return this.classCodeField;
            }
            set
            {
                this.classCodeField = value;
                this.RaisePropertyChanged("classCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual x_ActMoodDocumentObservation moodCode
        {
            get
            {
                return moodCodeField;
            }
            set
            {
                this.moodCodeField = value;
                this.RaisePropertyChanged("moodCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual bool negationInd
        {
            get
            {
                return this.negationIndField;
            }
            set
            {
                this.negationIndField = value;
                this.RaisePropertyChanged("negationInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool negationIndSpecified
        {
            get
            {
                return this.negationIndFieldSpecified;
            }
            set
            {
                this.negationIndFieldSpecified = value;
                this.RaisePropertyChanged("negationIndSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
