//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.Hl7.Cda
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XsdShell", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="POCD_MT000040.ClinicalDocument", Namespace="urn:hl7-org:v3")]
    [System.Xml.Serialization.XmlRootAttribute("ClinicalDocument", Namespace="urn:hl7-org:v3", IsNullable=false)]
    public partial class POCD_MT000040ClinicalDocument : CdaObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        private CSCollection realmCodeField;
        
        private POCD_MT000040InfrastructureRoottypeId typeIdField;
        
        private IICollection templateIdField;
        
        private II idField;
        
        private CE codeField;
        
        private ST titleField;
        
        private TS effectiveTimeField;
        
        private CE confidentialityCodeField;
        
        private CS languageCodeField;
        
        private II setIdField;
        
        private INT versionNumberField;
        
        private TS copyTimeField;
        
        private POCD_MT000040RecordTargetCollection recordTargetField;
        
        private POCD_MT000040AuthorCollection authorField;
        
        private POCD_MT000040DataEnterer dataEntererField;
        
        private POCD_MT000040Informant12Collection informantField;
        
        private POCD_MT000040Custodian custodianField;
        
        private POCD_MT000040InformationRecipientCollection informationRecipientField;
        
        private POCD_MT000040LegalAuthenticator legalAuthenticatorField;
        
        private POCD_MT000040AuthenticatorCollection authenticatorField;
        
        private POCD_MT000040Participant1Collection participantField;
        
        private POCD_MT000040InFulfillmentOfCollection inFulfillmentOfField;
        
        private POCD_MT000040DocumentationOfCollection documentationOfField;
        
        private POCD_MT000040RelatedDocumentCollection relatedDocumentField;
        
        private POCD_MT000040AuthorizationCollection authorizationField;
        
        private POCD_MT000040Component1 componentOfField;
        
        private POCD_MT000040Component2 componentField;
        
        private string nullFlavorField;
        
        private ActClinicalDocument classCodeField;
        
        private bool classCodeFieldSpecified;
        
        private string moodCodeField;
        
        public POCD_MT000040ClinicalDocument()
        {
            this.classCodeField = ActClinicalDocument.DOCCLIN;
            this.moodCodeField = "EVN";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("realmCode")]
        public virtual CSCollection realmCode
        {
            get
            {
                if (realmCodeField == null)
                {
                    this.realmCodeField = new CSCollection();
                }
                return realmCodeField;
            }
            set
            {
                this.realmCodeField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("realmCode");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual POCD_MT000040InfrastructureRoottypeId typeId
        {
            get
            {
                return typeIdField;
            }
            set
            {
                this.typeIdField = value;
                this.RaisePropertyChanged("typeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("templateId")]
        public virtual IICollection templateId
        {
            get
            {
                if (templateIdField == null)
                {
                    this.templateIdField = new IICollection();
                }
                return templateIdField;
            }
            set
            {
                this.templateIdField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("templateId");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual II id
        {
            get
            {
                return idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual CE code
        {
            get
            {
                return codeField;
            }
            set
            {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual ST title
        {
            get
            {
                return titleField;
            }
            set
            {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual TS effectiveTime
        {
            get
            {
                return effectiveTimeField;
            }
            set
            {
                this.effectiveTimeField = value;
                this.RaisePropertyChanged("effectiveTime");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual CE confidentialityCode
        {
            get
            {
                return confidentialityCodeField;
            }
            set
            {
                this.confidentialityCodeField = value;
                this.RaisePropertyChanged("confidentialityCode");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual CS languageCode
        {
            get
            {
                return languageCodeField;
            }
            set
            {
                this.languageCodeField = value;
                this.RaisePropertyChanged("languageCode");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual II setId
        {
            get
            {
                return setIdField;
            }
            set
            {
                this.setIdField = value;
                this.RaisePropertyChanged("setId");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual INT versionNumber
        {
            get
            {
                return versionNumberField;
            }
            set
            {
                this.versionNumberField = value;
                this.RaisePropertyChanged("versionNumber");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual TS copyTime
        {
            get
            {
                return copyTimeField;
            }
            set
            {
                this.copyTimeField = value;
                this.RaisePropertyChanged("copyTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recordTarget")]
        public virtual POCD_MT000040RecordTargetCollection recordTarget
        {
            get
            {
                if (recordTargetField == null)
                {
                    this.recordTargetField = new POCD_MT000040RecordTargetCollection();
                }
                return recordTargetField;
            }
            set
            {
                this.recordTargetField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("recordTarget");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("author")]
        public virtual POCD_MT000040AuthorCollection author
        {
            get
            {
                if (authorField == null)
                {
                    this.authorField = new POCD_MT000040AuthorCollection();
                }
                return authorField;
            }
            set
            {
                this.authorField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("author");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual POCD_MT000040DataEnterer dataEnterer
        {
            get
            {
                return dataEntererField;
            }
            set
            {
                this.dataEntererField = value;
                this.RaisePropertyChanged("dataEnterer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("informant")]
        public virtual POCD_MT000040Informant12Collection informant
        {
            get
            {
                if (informantField == null)
                {
                    this.informantField = new POCD_MT000040Informant12Collection();
                }
                return informantField;
            }
            set
            {
                this.informantField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("informant");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual POCD_MT000040Custodian custodian
        {
            get
            {
                return custodianField;
            }
            set
            {
                this.custodianField = value;
                this.RaisePropertyChanged("custodian");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("informationRecipient")]
        public virtual POCD_MT000040InformationRecipientCollection informationRecipient
        {
            get
            {
                if (informationRecipientField == null)
                {
                    this.informationRecipientField = new POCD_MT000040InformationRecipientCollection();
                }
                return informationRecipientField;
            }
            set
            {
                this.informationRecipientField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("informationRecipient");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual POCD_MT000040LegalAuthenticator legalAuthenticator
        {
            get
            {
                return legalAuthenticatorField;
            }
            set
            {
                this.legalAuthenticatorField = value;
                this.RaisePropertyChanged("legalAuthenticator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("authenticator")]
        public virtual POCD_MT000040AuthenticatorCollection authenticator
        {
            get
            {
                if (authenticatorField == null)
                {
                    this.authenticatorField = new POCD_MT000040AuthenticatorCollection();
                }
                return authenticatorField;
            }
            set
            {
                this.authenticatorField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("authenticator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("participant")]
        public virtual POCD_MT000040Participant1Collection participant
        {
            get
            {
                if (participantField == null)
                {
                    this.participantField = new POCD_MT000040Participant1Collection();
                }
                return participantField;
            }
            set
            {
                this.participantField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("participant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inFulfillmentOf")]
        public virtual POCD_MT000040InFulfillmentOfCollection inFulfillmentOf
        {
            get
            {
                if (inFulfillmentOfField == null)
                {
                    this.inFulfillmentOfField = new POCD_MT000040InFulfillmentOfCollection();
                }
                return inFulfillmentOfField;
            }
            set
            {
                this.inFulfillmentOfField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("inFulfillmentOf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("documentationOf")]
        public virtual POCD_MT000040DocumentationOfCollection documentationOf
        {
            get
            {
                if (documentationOfField == null)
                {
                    this.documentationOfField = new POCD_MT000040DocumentationOfCollection();
                }
                return documentationOfField;
            }
            set
            {
                this.documentationOfField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("documentationOf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relatedDocument")]
        public virtual POCD_MT000040RelatedDocumentCollection relatedDocument
        {
            get
            {
                if (relatedDocumentField == null)
                {
                    this.relatedDocumentField = new POCD_MT000040RelatedDocumentCollection();
                }
                return relatedDocumentField;
            }
            set
            {
                this.relatedDocumentField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("relatedDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("authorization")]
        public virtual POCD_MT000040AuthorizationCollection authorization
        {
            get
            {
                if (authorizationField == null)
                {
                    this.authorizationField = new POCD_MT000040AuthorizationCollection();
                }
                return authorizationField;
            }
            set
            {
                this.authorizationField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("authorization");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual POCD_MT000040Component1 componentOf
        {
            get
            {
                return componentOfField;
            }
            set
            {
                this.componentOfField = value;
                this.RaisePropertyChanged("componentOf");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual POCD_MT000040Component2 component
        {
            get
            {
                return componentField;
            }
            set
            {
                this.componentField = value;
                this.RaisePropertyChanged("component");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual string nullFlavor
        {
            get
            {
                return this.nullFlavorField;
            }
            set
            {
                this.nullFlavorField = value;
                this.RaisePropertyChanged("nullFlavor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual ActClinicalDocument classCode
        {
            get
            {
                return classCodeField;
            }
            set
            {
                this.classCodeField = value;
                this.RaisePropertyChanged("classCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool classCodeSpecified
        {
            get
            {
                return this.classCodeFieldSpecified;
            }
            set
            {
                this.classCodeFieldSpecified = value;
                this.RaisePropertyChanged("classCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual string moodCode
        {
            get
            {
                return this.moodCodeField;
            }
            set
            {
                this.moodCodeField = value;
                this.RaisePropertyChanged("moodCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
