//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.Hl7.Cda
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XsdShell", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:v3")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:v3", IsNullable=true)]
    public partial class SLIST_TS : ANY
    {
        
        private TS originField;
        
        private PQ scaleField;
        
        private string digitsField;
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual TS origin
        {
            get
            {
                return originField;
            }
            set
            {
                this.originField = value;
                this.RaisePropertyChanged("origin");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual PQ scale
        {
            get
            {
                return scaleField;
            }
            set
            {
                this.scaleField = value;
                this.RaisePropertyChanged("scale");
            }
        }
        
        /// <remarks/>
        public virtual string digits
        {
            get
            {
                return this.digitsField;
            }
            set
            {
                this.digitsField = value;
                this.RaisePropertyChanged("digits");
            }
        }
    }
}
