//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcline.Hl7.Cda
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XsdShell", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="StrucDoc.Table", Namespace="urn:hl7-org:v3")]
    [System.Xml.Serialization.XmlRootAttribute("StrucDoc.Table", Namespace="urn:hl7-org:v3", IsNullable=true)]
    public partial class StrucDocTable : CdaObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        private StrucDocCaption captionField;
        
        private object[] itemsField;
        
        private StrucDocThead theadField;
        
        private StrucDocTfoot tfootField;
        
        private StrucDocTbodyCollection tbodyField;
        
        private string idField;
        
        private string languageField;
        
        private string styleCodeField;
        
        private string summaryField;
        
        private string widthField;
        
        private string borderField;
        
        private StrucDocTableFrame frameField;
        
        private bool frameFieldSpecified;
        
        private StrucDocTableRules rulesField;
        
        private bool rulesFieldSpecified;
        
        private string cellspacingField;
        
        private string cellpaddingField;
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual StrucDocCaption caption
        {
            get
            {
                return captionField;
            }
            set
            {
                this.captionField = value;
                this.RaisePropertyChanged("caption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("col", typeof(StrucDocCol))]
        [System.Xml.Serialization.XmlElementAttribute("colgroup", typeof(StrucDocColgroup))]
        public virtual object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual StrucDocThead thead
        {
            get
            {
                return theadField;
            }
            set
            {
                this.theadField = value;
                this.RaisePropertyChanged("thead");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.TypeConverter(typeof(System.ComponentModel.ExpandableObjectConverter))]
        public virtual StrucDocTfoot tfoot
        {
            get
            {
                return tfootField;
            }
            set
            {
                this.tfootField = value;
                this.RaisePropertyChanged("tfoot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tbody")]
        public virtual StrucDocTbodyCollection tbody
        {
            get
            {
                if (tbodyField == null)
                {
                    this.tbodyField = new StrucDocTbodyCollection();
                }
                return tbodyField;
            }
            set
            {
                this.tbodyField = value;
                if (value != null)
                {
                }
                this.RaisePropertyChanged("tbody");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public virtual string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public virtual string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKENS")]
        public virtual string styleCode
        {
            get
            {
                return this.styleCodeField;
            }
            set
            {
                this.styleCodeField = value;
                this.RaisePropertyChanged("styleCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual string summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
                this.RaisePropertyChanged("summary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual string width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual string border
        {
            get
            {
                return this.borderField;
            }
            set
            {
                this.borderField = value;
                this.RaisePropertyChanged("border");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual StrucDocTableFrame frame
        {
            get
            {
                return frameField;
            }
            set
            {
                this.frameField = value;
                this.RaisePropertyChanged("frame");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool frameSpecified
        {
            get
            {
                return this.frameFieldSpecified;
            }
            set
            {
                this.frameFieldSpecified = value;
                this.RaisePropertyChanged("frameSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual StrucDocTableRules rules
        {
            get
            {
                return rulesField;
            }
            set
            {
                this.rulesField = value;
                this.RaisePropertyChanged("rules");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool rulesSpecified
        {
            get
            {
                return this.rulesFieldSpecified;
            }
            set
            {
                this.rulesFieldSpecified = value;
                this.RaisePropertyChanged("rulesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual string cellspacing
        {
            get
            {
                return this.cellspacingField;
            }
            set
            {
                this.cellspacingField = value;
                this.RaisePropertyChanged("cellspacing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public virtual string cellpadding
        {
            get
            {
                return this.cellpaddingField;
            }
            set
            {
                this.cellpaddingField = value;
                this.RaisePropertyChanged("cellpadding");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
